In [7]:
from transformers import MarkupLMFeatureExtractor


Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


/Users/muneebmuhammad/opt/anaconda3/envs/seleniumScrap/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Feature Extractor

In [43]:
with open("/Users/muneebmuhammad/Desktop/Dashboard - ConvertKit.html") as f:
    single_html_string = f.read()

feature_extractor = MarkupLMFeatureExtractor()

html_string = """
 <!DOCTYPE html>
 <html>
 <head>
 <title>Hello world</title>
 </head>
 <body>
 <h1>Welcome</h1>
 <p>My name is Niels.</p>
 </body>
 </html>"""
# single example
encoding = feature_extractor(single_html_string)
print(encoding.keys())

dict_keys(['nodes', 'xpaths'])


In [44]:
encoding['nodes']

[['Dashboard - ConvertKit',
  'ConvertKit',
  'Grow',
  'Send',
  'Automate',
  'Earn',
  'Learn',
  'Menu',
  'Trial: 14 days remaining',
  'Upgrade now',
  'Muneeb',
  'Welcome to ConvertKit, Muneeb',
  'New Subscribers',
  'Go to subscribers',
  'Today',
  '1',
  'Past 7 days',
  '1',
  'Past 30 days',
  '1',
  'Total',
  '1',
  'Most recent subscribers',
  'a',
  'muneebkhattak57@gmail.com',
  'Imported July 10, 2023',
  'Create a new...',
  'Watch your welcome video',
  'You’ve logged in to a different account!',
  'It looks like you are in two accounts at once. To prevent losing any work, please select the account you wish to proceed with:',
  'mmuhammad.bscs20seecs@seecs.edu.pk',
  'Use account from other tab',
  'Subscribers',
  'Browse all your subscribers and customers.',
  'Creator Profile',
  'Your hub on the internet. A one-stop-shop for your subscribers to find all your content & products.',
  'Landing Pages & Forms',
  'Gather subscribers with a hosted landing page or a 

In [45]:
encoding['nodes'][0]
with open('../datasets/datasetV3/39/content1.txt', 'w') as f:
    f.write(' '.join(encoding['nodes'][0]))

In [15]:
encoding['xpaths'][0]

['/html/head/title', '/html/body/h1', '/html/body/p']

### Processor

In [16]:
from transformers import MarkupLMProcessor

processor = MarkupLMProcessor.from_pretrained("microsoft/markuplm-base")

In [62]:
html_string = """
 <!DOCTYPE html>
 <html>
 <head>
 <title>Hello world</title>
 </head>
 <body>
 <h1>Welcome</h1>
 <p>I am Muneeb</p>
 </body>
 </html>"""

question = "What is the name"
encoding = processor(html_string, questions=question, return_tensors="pt")
print(encoding.keys())

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'xpath_tags_seq', 'xpath_subs_seq'])


In [65]:
encoding['token_type_ids']

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
len(encoding['input_ids'][0]), len(encoding['xpath_tags_seq'][0]), len(encoding['xpath_subs_seq'][0])

(15, 15, 15)

In [56]:
encoding['input_ids'][0]

tensor([    0,  2264,    16,     5,   766,     2, 31414,   232, 25194,   100,
          524,  6760,  1942,   428,     2])

In [57]:
encoding['xpath_tags_seq'][0]

tensor([[216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216],
        [216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216],
        [216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216],
        [216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 216,
         216, 216, 216, 216, 216, 216, 216, 216, 216, 216, 2

In [58]:
encoding['xpath_tags_seq'][0][2] == encoding['xpath_tags_seq'][0][3]

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True])

In [59]:
encoding['xpath_subs_seq'][0]

tensor([[1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001],
        [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001],
        [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
         1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 10

### Model

In [50]:
from transformers import MarkupLMModel, MarkupLMConfig

# Initializing a MarkupLM microsoft/markuplm-base style configuration
configuration = MarkupLMConfig()

# Initializing a model from the microsoft/markuplm-base style configuration
model = MarkupLMModel(configuration)

# Accessing the model configuration
configuration = model.config

In [52]:
configuration

MarkupLMConfig {
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_depth": 50,
  "max_position_embeddings": 512,
  "max_xpath_subs_unit_embeddings": 1024,
  "max_xpath_tag_unit_embeddings": 256,
  "model_type": "markuplm",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "subs_pad_id": 1001,
  "tag_pad_id": 216,
  "transformers_version": "4.24.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522,
  "xpath_unit_hidden_size": 32
}

In [51]:
model

MarkupLMModel(
  (embeddings): MarkupLMEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768, padding_idx=0)
    (xpath_embeddings): XPathEmbeddings(
      (xpath_unitseq2_embeddings): Linear(in_features=1600, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (activation): ReLU()
      (xpath_unitseq2_inner): Linear(in_features=1600, out_features=3072, bias=True)
      (inner2emb): Linear(in_features=3072, out_features=768, bias=True)
      (xpath_tag_sub_embeddings): ModuleList(
        (0-49): 50 x Embedding(256, 32)
      )
      (xpath_subs_sub_embeddings): ModuleList(
        (0-49): 50 x Embedding(1024, 32)
      )
    )
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): MarkupLMEncoder(
    (layer): ModuleList(
      (0-11): 12 x MarkupLMLayer(
        (atte

In [66]:
from transformers import AutoProcessor, MarkupLMModel

processor = AutoProcessor.from_pretrained("microsoft/markuplm-base")
model = MarkupLMModel.from_pretrained("microsoft/markuplm-base")

html_string = "<html> <head> <title>Page Title</title> </head> </html>"

encoding = processor(html_string, return_tensors="pt")

outputs = model(**encoding)
outputs

Some weights of the model checkpoint at microsoft/markuplm-base were not used when initializing MarkupLMModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'nrp_cls.dense.bias', 'ptc_cls.bias', 'cls.predictions.transform.dense.weight', 'nrp_cls.LayerNorm.bias', 'ptc_cls.weight', 'cls.predictions.decoder.bias', 'nrp_cls.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'nrp_cls.dense.weight', 'nrp_cls.decoder.weight', 'nrp_cls.LayerNorm.weight']
- This IS expected if you are initializing MarkupLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing MarkupLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClas

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0691,  0.0568,  0.5247,  ..., -0.0421,  0.1532,  0.5823],
         [-0.3715, -0.1436,  0.5005,  ..., -0.7094,  0.5908,  0.8812],
         [ 0.0513, -0.4670,  0.1915,  ...,  0.6557,  0.2499,  0.7537],
         [-0.4292, -0.0060,  0.1642,  ..., -0.0242, -0.4538,  0.3002]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 8.0469e-01, -1.9732e-01, -9.0661e-01,  5.9489e-02,  9.2041e-01,
         -9.9707e-02, -6.4377e-02,  2.1215e-03,  4.8670e-01, -1.9845e-01,
          5.9599e-02,  1.3155e-01, -3.6861e-02, -9.7172e-01, -9.8506e-01,
          9.2989e-01, -4.0714e-01, -9.5633e-01, -4.6189e-01, -4.9544e-01,
         -1.2060e-01,  1.1836e-01, -1.7348e-01,  2.7105e-01,  2.9364e-01,
         -4.5277e-02, -1.1718e-01, -8.0328e-02,  1.0154e-01,  1.0720e-01,
         -1.1623e-01, -8.0564e-02,  1.8447e-01,  9.8975e-01, -2.9377e-02,
          3.3360e-01,  1.1292e-01,  1.0241e-01, -7.8454e-02,  5.3558e-03,
 

### Question Answering Model

In [5]:
from transformers import AutoProcessor, MarkupLMForQuestionAnswering
import torch

processor = AutoProcessor.from_pretrained("microsoft/markuplm-base-finetuned-websrc")
model = MarkupLMForQuestionAnswering.from_pretrained("microsoft/markuplm-base-finetuned-websrc")

html_string = "<html> <head> <title>My name is Niels</title> </head> <body> I study in Pakistan</body> </html>"
question = "What is the name of website?"

encoding = processor(single_html_string, questions=question, return_tensors="pt", truncation=True)

In [6]:
encoding.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'xpath_tags_seq', 'xpath_subs_seq'])

In [8]:
len(encoding['input_ids'][0])

512

In [102]:
with torch.no_grad():
    outputs = model(**encoding)

In [103]:
answer_start_index = outputs.start_logits.argmax()
answer_end_index = outputs.end_logits.argmax()

predict_answer_tokens = encoding.input_ids[0, answer_start_index : answer_end_index + 1]
processor.decode(predict_answer_tokens).strip()

'<s>'

In [104]:
encoding.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'xpath_tags_seq', 'xpath_subs_seq'])

In [107]:
len(encoding['input_ids'][0])

56

### Generate data for MarkupLM from version1 dataset

In [28]:
import os
import shutil

In [13]:
# Updated function to remove leading whitespace from each line
def remove_before_colon(text):
    lines = text.split('\n')
    new_lines = []
    for line in lines:
        # Only process non-empty lines
        if line:
            index = line.find(': ')
            if index != -1:
                # Skip the content before and including ": ", and remove leading whitespace
                new_line = line[index+2:].lstrip()
                new_lines.append(new_line)
            else:
                new_lines.append(line)
    return '\n'.join(new_lines)

def remove_input_lines(text):
    lines = text.split('\n')
    new_lines = [line for line in lines if not line.startswith('input')]
    return '\n'.join(new_lines)


In [38]:
with open("../../../../../Desktop/Dashboard - ConvertKit.html", "r") as f:
    t = f.read()
    o = remove_input_lines(t)
    o = remove_before_colon(o)
    
print(o)

<!DOCTYPE html>
<!-- saved from url=(0036)https://app.convertkit.com/dashboard -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style type="text/css">svg:not(:root).svg-inline--fa {
visible;
}
.svg-inline--fa {
inline-block;
inherit;
1em;
visible;
-0.125em;
}
.svg-inline--fa.fa-lg {
-0.225em;
}
.svg-inline--fa.fa-w-1 {
0.0625em;
}
.svg-inline--fa.fa-w-2 {
0.125em;
}
.svg-inline--fa.fa-w-3 {
0.1875em;
}
.svg-inline--fa.fa-w-4 {
0.25em;
}
.svg-inline--fa.fa-w-5 {
0.3125em;
}
.svg-inline--fa.fa-w-6 {
0.375em;
}
.svg-inline--fa.fa-w-7 {
0.4375em;
}
.svg-inline--fa.fa-w-8 {
0.5em;
}
.svg-inline--fa.fa-w-9 {
0.5625em;
}
.svg-inline--fa.fa-w-10 {
0.625em;
}
.svg-inline--fa.fa-w-11 {
0.6875em;
}
.svg-inline--fa.fa-w-12 {
0.75em;
}
.svg-inline--fa.fa-w-13 {
0.8125em;
}
.svg-inline--fa.fa-w-14 {
0.875em;
}
.svg-inline--fa.fa-w-15 {
0.9375em;
}
.svg-inline--fa.fa-w-16 {
1em;
}
.svg-inline--fa.fa-w-17 {
1.0625em;
}
.svg-inline--fa.fa-w-18 {
1.125em;
}
.

In [30]:
folder_path = "../datasets/datasetV1/final_dataset1/"
output_folder = "../datasets/datasetV3/"
for folder in os.listdir(folder_path):
    # check if it's a directory
    if os.path.isdir(os.path.join(folder_path, folder)):
        # paths to the files
        dom_path = os.path.join(folder_path, folder, 'DOM.txt')
        response_path = os.path.join(folder_path, folder, 'response.txt')
        os.makedirs(os.path.join(output_folder, folder), exist_ok=True)
        output_path = os.path.join(output_folder, folder, "output.txt")
        shutil.copy(os.path.join(folder_path, folder, "instruction.txt"), os.path.join(output_folder, folder, "instruction.txt"))
        try:
            with open(dom_path, 'r') as dom_file, open(response_path, 'r') as response_file:
                domTexts = dom_file.read()
                domTexts = remove_input_lines(domTexts)
                domTexts = remove_before_colon(domTexts)
                with open(os.path.join(output_folder, folder, "content.txt"), 'w') as contentFile:
                    contentFile.write(domTexts.replace("\n", " "))
                dom_lines = domTexts.split('\n')
                # dom_lines = dom_file.readlines()
                response_lines = [int(line.strip()) for line in response_file.readlines()]
                
                # compute the cumulative word counts
                cum_word_counts = [len(' '.join(dom_lines[:i+1]).split()) for i in range(len(dom_lines))]
                
                # create the output file
                with open(output_path, 'w') as output_file:
                    for line_num in response_lines:
                        line_num -=1
                        # check if line number is within the range
                        if line_num < len(dom_lines):
                            words_in_line = len(dom_lines[line_num].split())
                            start_word_count = cum_word_counts[line_num] - words_in_line
                            end_word_count = cum_word_counts[line_num]
                            output_file.write(f'{start_word_count},{end_word_count}\n')

        except:
            with open(dom_path, 'r', encoding='ISO-8859-1') as dom_file, open(response_path, 'r') as response_file:
                domTexts = dom_file.read()
                domTexts = remove_input_lines(t)
                domTexts = remove_before_colon(o)
                with open(os.path.join(output_folder, folder, "content.txt"), 'w') as contentFile:
                    contentFile.write(domTexts.replace("\n", " "))
                dom_lines = domTexts.split('\n')
                # dom_lines = dom_file.readlines()
                response_lines = [int(line.strip()) for line in response_file.readlines()]
                
                # compute the cumulative word counts
                cum_word_counts = [len(' '.join(dom_lines[:i+1]).split()) for i in range(len(dom_lines))]
                
                # create the output file
                with open(output_path, 'w') as output_file:
                    for line_num in response_lines:
                        line_num -=1
                        # check if line number is within the range
                        if line_num < len(dom_lines):
                            words_in_line = len(dom_lines[line_num].split())
                            start_word_count = cum_word_counts[line_num] - words_in_line
                            end_word_count = cum_word_counts[line_num]
                            output_file.write(f'{start_word_count},{end_word_count}\n')
    

### Create markupLM dataset from raw html. Processing is also done

In [61]:
from transformers import MarkupLMFeatureExtractor
import os
from bs4 import BeautifulSoup, NavigableString

In [79]:
def remove_long_text_nodes(html):
    soup = BeautifulSoup(html, 'html.parser')

    for node in soup.find_all():
        if node.string is not None:
            word_count = len(node.string.split())
            if word_count > 20:
                node.string.replace_with('')

    return str(soup.prettify())

In [80]:
# goes to the folder and reads html file then writes the content of html in "content.txt" file
folder = "../datasets/datasetV3/40"

files = os.listdir(folder)
# find the HTML file
html_file = next((f for f in files if f.endswith('.html')), None)
html_file_path = os.path.join(folder, html_file)
with open(html_file_path, "r") as f:
    single_html_string = f.read()

# shortern the html
single_html_string = remove_long_text_nodes(single_html_string)

with open(os.path.join(folder, "DOM.txt"), "w") as f:
    f.write(single_html_string)
feature_extractor = MarkupLMFeatureExtractor()
# single example
encoding = feature_extractor(str(single_html_string))
with open(f"{folder}/content.txt", "w") as f:
    f.write(' '.join(encoding['nodes'][0]))

In [73]:
encoding['xpaths'][0]

['/html/head/title',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/a/span',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/nav/button[1]',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/nav/button[2]',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/nav/button[3]',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/nav/button[4]',
 '/html/body/div[1]/div/div[1]/div/div/div/div[1]/nav/button[5]',
 '/html/body/div[1]/div/div[1]/div/div/div/div[2]/button',
 '/html/body/div[1]/div/div[1]/div/div/div/div[3]/div[2]/div',
 '/html/body/div[1]/div/div[1]/div/div/div/div[3]/div[2]/a',
 '/html/body/div[1]/div/div[1]/div/div/div/div[3]/button/span',
 '/html/body/div[1]/div/div[5]/div/div/div/a[1]/span',
 '/html/body/div[1]/div/div[5]/div/div/div/a[2]/span',
 '/html/body/div[1]/div/div[5]/div/div/div/a[3]/span',
 '/html/body/div[1]/div/div[5]/div/div/div/a[4]/span',
 '/html/body/div[4]/div/div/div[2]/div/div/div[1]/a',
 '/html/body/div[4]/div/div/div[2]/div/div/div[2]/a',
 '/html/body/re

In [78]:
encoding['nodes'][0]

['Choose Format - ConvertKit',
 'ConvertKit',
 'Grow',
 'Send',
 'Automate',
 'Earn',
 'Learn',
 'Menu',
 'Trial: 14 days remaining',
 'Upgrade now',
 'Muneeb',
 'Enable email sending & form subscriptions',
 'Describe your business or blog topic in a sentence or two',
 "Thanks for submitting a request for account approval. We'll reach out to you within the next few hours.",
 'Choose the display format of this form',
 'Inline',
 'Modal',
 'Slide in',
 'Sticky bar',
 '© 2013 - 2023 ConvertKit. All Rights Reserved.',
 'You’ve logged in to a different account!',
 'mmuhammad.bscs20seecs@seecs.edu.pk',
 'Use account from other tab',
 'Subscribers',
 'Browse all your subscribers and customers.',
 'Creator Profile',
 'Your hub on the internet. A one-stop-shop for your subscribers to find all your content & products.',
 'Landing Pages & Forms',
 'Gather subscribers with a hosted landing page or a form embedded on your website.',
 'Creator Network',
 'Find creators to partner with to grow your a